# Generated by Django 6.0.5 on 2026-05-22 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_event_sermon_testimony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='video',
        ),
        migrations.AddField(
            model_name='sermon',
            name='video_url',
            field=models.URLField(default=django.utils.timezone.now, help_text='Paste YouTube, TikTok, Facebook, or any sermon video link.', max_length=500),
            preserve_default=False,
        ),
    ]
