# Generated by Django 6.0.5 on 2026-05-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_sermon_video_sermon_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='thumbnail',
        ),
    ]
