# Generated by Django 6.0.5 on 2026-05-26 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_childprofile_childrenprogram_impactstory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImpactStory',
        ),
        migrations.AlterModelOptions(
            name='childprofile',
            options={'ordering': ['-featured', 'name']},
        ),
        migrations.RenameField(
            model_name='childprofile',
            old_name='is_featured',
            new_name='featured',
        ),
        migrations.RenameField(
            model_name='childprofile',
            old_name='short_story',
            new_name='story',
        ),
        migrations.AddField(
            model_name='childprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childprofile',
            name='dream',
            field=models.CharField(default='To become a doctor', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childprofile',
            name='favorite_subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childprofile',
            name='school',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='scripture',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='sponsorship_level',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], default='Bronze', max_length=20),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='sponsorship_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sponsored', 'Sponsored')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='children/'),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='needs',
            field=models.TextField(blank=True, help_text='School fees, clothing, food, medical support, etc.'),
        ),
    ]
