# Generated by Django 6.0.5 on 2026-05-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delete_impactstory_alter_childprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('purpose', models.CharField(choices=[('Tithe', 'Tithe'), ('Offering', 'Offering'), ('Children Ministry', 'Children Ministry'), ('Outreach', 'Outreach'), ('General Support', 'General Support')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ChildrenProgram',
        ),
    ]
