# Generated by Django 6.0.5 on 2026-05-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_givepartner_delete_childrenprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Offering'), ('children_ministry', "Children's Ministry"), ('outreach', 'Outreach'), ('general_support', 'General Support')], max_length=50)),
                ('network', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money')], max_length=20)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GivePartner',
        ),
    ]
